'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace GeocodeService
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="RequestBase", [Namespace]:="http://dev.virtualearth.net/webservices/v1/common"),  _
     System.SerializableAttribute(),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(GeocodeService.ReverseGeocodeRequest)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(GeocodeService.GeocodeRequest))>  _
    Partial Public Class RequestBase
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CredentialsField As Microsoft.Maps.MapControl.WPF.Credentials
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CultureField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ExecutionOptionsField As GeocodeService.ExecutionOptions
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UserProfileField As GeocodeService.UserProfile
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Credentials() As Microsoft.Maps.MapControl.WPF.Credentials
            Get
                Return Me.CredentialsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CredentialsField, value) <> true) Then
                    Me.CredentialsField = value
                    Me.RaisePropertyChanged("Credentials")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Culture() As String
            Get
                Return Me.CultureField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CultureField, value) <> true) Then
                    Me.CultureField = value
                    Me.RaisePropertyChanged("Culture")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ExecutionOptions() As GeocodeService.ExecutionOptions
            Get
                Return Me.ExecutionOptionsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ExecutionOptionsField, value) <> true) Then
                    Me.ExecutionOptionsField = value
                    Me.RaisePropertyChanged("ExecutionOptions")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UserProfile() As GeocodeService.UserProfile
            Get
                Return Me.UserProfileField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UserProfileField, value) <> true) Then
                    Me.UserProfileField = value
                    Me.RaisePropertyChanged("UserProfile")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ExecutionOptions", [Namespace]:="http://dev.virtualearth.net/webservices/v1/common"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ExecutionOptions
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SuppressFaultsField As Boolean
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SuppressFaults() As Boolean
            Get
                Return Me.SuppressFaultsField
            End Get
            Set
                If (Me.SuppressFaultsField.Equals(value) <> true) Then
                    Me.SuppressFaultsField = value
                    Me.RaisePropertyChanged("SuppressFaults")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="UserProfile", [Namespace]:="http://dev.virtualearth.net/webservices/v1/common"),  _
     System.SerializableAttribute()>  _
    Partial Public Class UserProfile
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CurrentHeadingField As GeocodeService.Heading
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CurrentLocationField As GeocodeService.UserLocation
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DeviceTypeField As GeocodeService.DeviceType
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DistanceUnitField As GeocodeService.DistanceUnit
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IPAddressField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MapViewField As GeocodeService.ShapeBase
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ScreenSizeField As GeocodeService.SizeOfint
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CurrentHeading() As GeocodeService.Heading
            Get
                Return Me.CurrentHeadingField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CurrentHeadingField, value) <> true) Then
                    Me.CurrentHeadingField = value
                    Me.RaisePropertyChanged("CurrentHeading")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CurrentLocation() As GeocodeService.UserLocation
            Get
                Return Me.CurrentLocationField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CurrentLocationField, value) <> true) Then
                    Me.CurrentLocationField = value
                    Me.RaisePropertyChanged("CurrentLocation")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DeviceType() As GeocodeService.DeviceType
            Get
                Return Me.DeviceTypeField
            End Get
            Set
                If (Me.DeviceTypeField.Equals(value) <> true) Then
                    Me.DeviceTypeField = value
                    Me.RaisePropertyChanged("DeviceType")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DistanceUnit() As GeocodeService.DistanceUnit
            Get
                Return Me.DistanceUnitField
            End Get
            Set
                If (Me.DistanceUnitField.Equals(value) <> true) Then
                    Me.DistanceUnitField = value
                    Me.RaisePropertyChanged("DistanceUnit")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IPAddress() As String
            Get
                Return Me.IPAddressField
            End Get
            Set
                If (Object.ReferenceEquals(Me.IPAddressField, value) <> true) Then
                    Me.IPAddressField = value
                    Me.RaisePropertyChanged("IPAddress")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property MapView() As GeocodeService.ShapeBase
            Get
                Return Me.MapViewField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MapViewField, value) <> true) Then
                    Me.MapViewField = value
                    Me.RaisePropertyChanged("MapView")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ScreenSize() As GeocodeService.SizeOfint
            Get
                Return Me.ScreenSizeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ScreenSizeField, value) <> true) Then
                    Me.ScreenSizeField = value
                    Me.RaisePropertyChanged("ScreenSize")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ReverseGeocodeRequest", [Namespace]:="http://dev.virtualearth.net/webservices/v1/geocode"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ReverseGeocodeRequest
        Inherits GeocodeService.RequestBase
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LocationField As GeocodeService.Location
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Location() As GeocodeService.Location
            Get
                Return Me.LocationField
            End Get
            Set
                If (Object.ReferenceEquals(Me.LocationField, value) <> true) Then
                    Me.LocationField = value
                    Me.RaisePropertyChanged("Location")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="GeocodeRequest", [Namespace]:="http://dev.virtualearth.net/webservices/v1/geocode"),  _
     System.SerializableAttribute()>  _
    Partial Public Class GeocodeRequest
        Inherits GeocodeService.RequestBase
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AddressField As GeocodeService.Address
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OptionsField As GeocodeService.GeocodeOptions
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private QueryField As String
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Address() As GeocodeService.Address
            Get
                Return Me.AddressField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AddressField, value) <> true) Then
                    Me.AddressField = value
                    Me.RaisePropertyChanged("Address")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Options() As GeocodeService.GeocodeOptions
            Get
                Return Me.OptionsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.OptionsField, value) <> true) Then
                    Me.OptionsField = value
                    Me.RaisePropertyChanged("Options")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Query() As String
            Get
                Return Me.QueryField
            End Get
            Set
                If (Object.ReferenceEquals(Me.QueryField, value) <> true) Then
                    Me.QueryField = value
                    Me.RaisePropertyChanged("Query")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Address", [Namespace]:="http://dev.virtualearth.net/webservices/v1/common"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Address
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AddressLineField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AdminDistrictField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CountryRegionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DistrictField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FormattedAddressField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LocalityField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PostalCodeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PostalTownField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AddressLine() As String
            Get
                Return Me.AddressLineField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AddressLineField, value) <> true) Then
                    Me.AddressLineField = value
                    Me.RaisePropertyChanged("AddressLine")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AdminDistrict() As String
            Get
                Return Me.AdminDistrictField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AdminDistrictField, value) <> true) Then
                    Me.AdminDistrictField = value
                    Me.RaisePropertyChanged("AdminDistrict")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CountryRegion() As String
            Get
                Return Me.CountryRegionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CountryRegionField, value) <> true) Then
                    Me.CountryRegionField = value
                    Me.RaisePropertyChanged("CountryRegion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property District() As String
            Get
                Return Me.DistrictField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DistrictField, value) <> true) Then
                    Me.DistrictField = value
                    Me.RaisePropertyChanged("District")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FormattedAddress() As String
            Get
                Return Me.FormattedAddressField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FormattedAddressField, value) <> true) Then
                    Me.FormattedAddressField = value
                    Me.RaisePropertyChanged("FormattedAddress")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Locality() As String
            Get
                Return Me.LocalityField
            End Get
            Set
                If (Object.ReferenceEquals(Me.LocalityField, value) <> true) Then
                    Me.LocalityField = value
                    Me.RaisePropertyChanged("Locality")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PostalCode() As String
            Get
                Return Me.PostalCodeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PostalCodeField, value) <> true) Then
                    Me.PostalCodeField = value
                    Me.RaisePropertyChanged("PostalCode")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PostalTown() As String
            Get
                Return Me.PostalTownField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PostalTownField, value) <> true) Then
                    Me.PostalTownField = value
                    Me.RaisePropertyChanged("PostalTown")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="GeocodeOptions", [Namespace]:="http://dev.virtualearth.net/webservices/v1/geocode"),  _
     System.SerializableAttribute()>  _
    Partial Public Class GeocodeOptions
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CountField As System.Nullable(Of Integer)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FiltersField() As GeocodeService.FilterBase
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Count() As System.Nullable(Of Integer)
            Get
                Return Me.CountField
            End Get
            Set
                If (Me.CountField.Equals(value) <> true) Then
                    Me.CountField = value
                    Me.RaisePropertyChanged("Count")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Filters() As GeocodeService.FilterBase()
            Get
                Return Me.FiltersField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FiltersField, value) <> true) Then
                    Me.FiltersField = value
                    Me.RaisePropertyChanged("Filters")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Heading", [Namespace]:="http://dev.virtualearth.net/webservices/v1/common"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Heading
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OrientationField As Double
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Orientation() As Double
            Get
                Return Me.OrientationField
            End Get
            Set
                If (Me.OrientationField.Equals(value) <> true) Then
                    Me.OrientationField = value
                    Me.RaisePropertyChanged("Orientation")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="UserLocation", [Namespace]:="http://dev.virtualearth.net/webservices/v1/common"),  _
     System.SerializableAttribute()>  _
    Partial Public Class UserLocation
        Inherits GeocodeService.Location
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ConfidenceField As GeocodeService.Confidence
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Confidence() As GeocodeService.Confidence
            Get
                Return Me.ConfidenceField
            End Get
            Set
                If (Me.ConfidenceField.Equals(value) <> true) Then
                    Me.ConfidenceField = value
                    Me.RaisePropertyChanged("Confidence")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ShapeBase", [Namespace]:="http://dev.virtualearth.net/webservices/v1/common"),  _
     System.SerializableAttribute(),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(GeocodeService.Rectangle)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(GeocodeService.Circle)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(GeocodeService.Polygon))>  _
    Partial Public Class ShapeBase
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="SizeOfint", [Namespace]:="http://dev.virtualearth.net/webservices/v1/common"),  _
     System.SerializableAttribute()>  _
    Partial Public Class SizeOfint
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private HeightField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private WidthField As Integer
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Height() As Integer
            Get
                Return Me.HeightField
            End Get
            Set
                If (Me.HeightField.Equals(value) <> true) Then
                    Me.HeightField = value
                    Me.RaisePropertyChanged("Height")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Width() As Integer
            Get
                Return Me.WidthField
            End Get
            Set
                If (Me.WidthField.Equals(value) <> true) Then
                    Me.WidthField = value
                    Me.RaisePropertyChanged("Width")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="DeviceType", [Namespace]:="http://dev.virtualearth.net/webservices/v1/common")>  _
    Public Enum DeviceType As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Desktop = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Mobile = 1
    End Enum
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="DistanceUnit", [Namespace]:="http://dev.virtualearth.net/webservices/v1/common")>  _
    Public Enum DistanceUnit As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Kilometer = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Mile = 1
    End Enum
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Location", [Namespace]:="http://dev.virtualearth.net/webservices/v1/common"),  _
     System.SerializableAttribute(),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(GeocodeService.GeocodeLocation)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(GeocodeService.UserLocation))>  _
    Partial Public Class Location
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AltitudeField As Double
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LatitudeField As Double
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LongitudeField As Double
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Altitude() As Double
            Get
                Return Me.AltitudeField
            End Get
            Set
                If (Me.AltitudeField.Equals(value) <> true) Then
                    Me.AltitudeField = value
                    Me.RaisePropertyChanged("Altitude")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Latitude() As Double
            Get
                Return Me.LatitudeField
            End Get
            Set
                If (Me.LatitudeField.Equals(value) <> true) Then
                    Me.LatitudeField = value
                    Me.RaisePropertyChanged("Latitude")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Longitude() As Double
            Get
                Return Me.LongitudeField
            End Get
            Set
                If (Me.LongitudeField.Equals(value) <> true) Then
                    Me.LongitudeField = value
                    Me.RaisePropertyChanged("Longitude")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="GeocodeLocation", [Namespace]:="http://dev.virtualearth.net/webservices/v1/common"),  _
     System.SerializableAttribute()>  _
    Partial Public Class GeocodeLocation
        Inherits GeocodeService.Location
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CalculationMethodField As String
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CalculationMethod() As String
            Get
                Return Me.CalculationMethodField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CalculationMethodField, value) <> true) Then
                    Me.CalculationMethodField = value
                    Me.RaisePropertyChanged("CalculationMethod")
                End If
            End Set
        End Property
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Confidence", [Namespace]:="http://dev.virtualearth.net/webservices/v1/common")>  _
    Public Enum Confidence As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        High = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Medium = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Low = 2
    End Enum
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Rectangle", [Namespace]:="http://dev.virtualearth.net/webservices/v1/common"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Rectangle
        Inherits GeocodeService.ShapeBase
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NortheastField As GeocodeService.Location
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SouthwestField As GeocodeService.Location
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Northeast() As GeocodeService.Location
            Get
                Return Me.NortheastField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NortheastField, value) <> true) Then
                    Me.NortheastField = value
                    Me.RaisePropertyChanged("Northeast")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Southwest() As GeocodeService.Location
            Get
                Return Me.SouthwestField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SouthwestField, value) <> true) Then
                    Me.SouthwestField = value
                    Me.RaisePropertyChanged("Southwest")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Circle", [Namespace]:="http://dev.virtualearth.net/webservices/v1/common"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Circle
        Inherits GeocodeService.ShapeBase
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CenterField As GeocodeService.Location
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DistanceUnitField As GeocodeService.DistanceUnit
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RadiusField As Double
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Center() As GeocodeService.Location
            Get
                Return Me.CenterField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CenterField, value) <> true) Then
                    Me.CenterField = value
                    Me.RaisePropertyChanged("Center")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DistanceUnit() As GeocodeService.DistanceUnit
            Get
                Return Me.DistanceUnitField
            End Get
            Set
                If (Me.DistanceUnitField.Equals(value) <> true) Then
                    Me.DistanceUnitField = value
                    Me.RaisePropertyChanged("DistanceUnit")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Radius() As Double
            Get
                Return Me.RadiusField
            End Get
            Set
                If (Me.RadiusField.Equals(value) <> true) Then
                    Me.RadiusField = value
                    Me.RaisePropertyChanged("Radius")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Polygon", [Namespace]:="http://dev.virtualearth.net/webservices/v1/common"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Polygon
        Inherits GeocodeService.ShapeBase
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private VerticesField() As GeocodeService.Location
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Vertices() As GeocodeService.Location()
            Get
                Return Me.VerticesField
            End Get
            Set
                If (Object.ReferenceEquals(Me.VerticesField, value) <> true) Then
                    Me.VerticesField = value
                    Me.RaisePropertyChanged("Vertices")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="FilterBase", [Namespace]:="http://dev.virtualearth.net/webservices/v1/geocode"),  _
     System.SerializableAttribute(),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(GeocodeService.ConfidenceFilter))>  _
    Partial Public Class FilterBase
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ConfidenceFilter", [Namespace]:="http://dev.virtualearth.net/webservices/v1/geocode"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ConfidenceFilter
        Inherits GeocodeService.FilterBase
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MinimumConfidenceField As GeocodeService.Confidence
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property MinimumConfidence() As GeocodeService.Confidence
            Get
                Return Me.MinimumConfidenceField
            End Get
            Set
                If (Me.MinimumConfidenceField.Equals(value) <> true) Then
                    Me.MinimumConfidenceField = value
                    Me.RaisePropertyChanged("MinimumConfidence")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ResponseBase", [Namespace]:="http://dev.virtualearth.net/webservices/v1/common"),  _
     System.SerializableAttribute(),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(GeocodeService.GeocodeResponse))>  _
    Partial Public Class ResponseBase
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private BrandLogoUriField As System.Uri
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ResponseSummaryField As GeocodeService.ResponseSummary
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property BrandLogoUri() As System.Uri
            Get
                Return Me.BrandLogoUriField
            End Get
            Set
                If (Object.ReferenceEquals(Me.BrandLogoUriField, value) <> true) Then
                    Me.BrandLogoUriField = value
                    Me.RaisePropertyChanged("BrandLogoUri")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ResponseSummary() As GeocodeService.ResponseSummary
            Get
                Return Me.ResponseSummaryField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ResponseSummaryField, value) <> true) Then
                    Me.ResponseSummaryField = value
                    Me.RaisePropertyChanged("ResponseSummary")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ResponseSummary", [Namespace]:="http://dev.virtualearth.net/webservices/v1/common"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ResponseSummary
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AuthenticationResultCodeField As GeocodeService.AuthenticationResultCode
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CopyrightField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FaultReasonField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StatusCodeField As GeocodeService.ResponseStatusCode
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TraceIdField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AuthenticationResultCode() As GeocodeService.AuthenticationResultCode
            Get
                Return Me.AuthenticationResultCodeField
            End Get
            Set
                If (Me.AuthenticationResultCodeField.Equals(value) <> true) Then
                    Me.AuthenticationResultCodeField = value
                    Me.RaisePropertyChanged("AuthenticationResultCode")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Copyright() As String
            Get
                Return Me.CopyrightField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CopyrightField, value) <> true) Then
                    Me.CopyrightField = value
                    Me.RaisePropertyChanged("Copyright")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FaultReason() As String
            Get
                Return Me.FaultReasonField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FaultReasonField, value) <> true) Then
                    Me.FaultReasonField = value
                    Me.RaisePropertyChanged("FaultReason")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property StatusCode() As GeocodeService.ResponseStatusCode
            Get
                Return Me.StatusCodeField
            End Get
            Set
                If (Me.StatusCodeField.Equals(value) <> true) Then
                    Me.StatusCodeField = value
                    Me.RaisePropertyChanged("StatusCode")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TraceId() As String
            Get
                Return Me.TraceIdField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TraceIdField, value) <> true) Then
                    Me.TraceIdField = value
                    Me.RaisePropertyChanged("TraceId")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="GeocodeResponse", [Namespace]:="http://dev.virtualearth.net/webservices/v1/geocode"),  _
     System.SerializableAttribute()>  _
    Partial Public Class GeocodeResponse
        Inherits GeocodeService.ResponseBase
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ResultsField() As GeocodeService.GeocodeResult
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Results() As GeocodeService.GeocodeResult()
            Get
                Return Me.ResultsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ResultsField, value) <> true) Then
                    Me.ResultsField = value
                    Me.RaisePropertyChanged("Results")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="GeocodeResult", [Namespace]:="http://dev.virtualearth.net/webservices/v1/common"),  _
     System.SerializableAttribute()>  _
    Partial Public Class GeocodeResult
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AddressField As GeocodeService.Address
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private BestViewField As GeocodeService.Rectangle
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ConfidenceField As GeocodeService.Confidence
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DisplayNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EntityTypeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LocationsField() As GeocodeService.GeocodeLocation
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MatchCodesField() As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Address() As GeocodeService.Address
            Get
                Return Me.AddressField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AddressField, value) <> true) Then
                    Me.AddressField = value
                    Me.RaisePropertyChanged("Address")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property BestView() As GeocodeService.Rectangle
            Get
                Return Me.BestViewField
            End Get
            Set
                If (Object.ReferenceEquals(Me.BestViewField, value) <> true) Then
                    Me.BestViewField = value
                    Me.RaisePropertyChanged("BestView")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Confidence() As GeocodeService.Confidence
            Get
                Return Me.ConfidenceField
            End Get
            Set
                If (Me.ConfidenceField.Equals(value) <> true) Then
                    Me.ConfidenceField = value
                    Me.RaisePropertyChanged("Confidence")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DisplayName() As String
            Get
                Return Me.DisplayNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DisplayNameField, value) <> true) Then
                    Me.DisplayNameField = value
                    Me.RaisePropertyChanged("DisplayName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EntityType() As String
            Get
                Return Me.EntityTypeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EntityTypeField, value) <> true) Then
                    Me.EntityTypeField = value
                    Me.RaisePropertyChanged("EntityType")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Locations() As GeocodeService.GeocodeLocation()
            Get
                Return Me.LocationsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.LocationsField, value) <> true) Then
                    Me.LocationsField = value
                    Me.RaisePropertyChanged("Locations")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property MatchCodes() As String()
            Get
                Return Me.MatchCodesField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MatchCodesField, value) <> true) Then
                    Me.MatchCodesField = value
                    Me.RaisePropertyChanged("MatchCodes")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="AuthenticationResultCode", [Namespace]:="http://dev.virtualearth.net/webservices/v1/common")>  _
    Public Enum AuthenticationResultCode As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        None = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        NoCredentials = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        ValidCredentials = 2
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        InvalidCredentials = 3
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        CredentialsExpired = 4
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        NotAuthorized = 7
    End Enum
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ResponseStatusCode", [Namespace]:="http://dev.virtualearth.net/webservices/v1/common")>  _
    Public Enum ResponseStatusCode As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Success = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        BadRequest = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        ServerError = 2
    End Enum
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://dev.virtualearth.net/webservices/v1/geocode/contracts", ConfigurationName:="GeocodeService.IGeocodeService")>  _
    Public Interface IGeocodeService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://dev.virtualearth.net/webservices/v1/geocode/contracts/IGeocodeService/Geoc"& _ 
            "ode", ReplyAction:="http://dev.virtualearth.net/webservices/v1/geocode/contracts/IGeocodeService/Geoc"& _ 
            "odeResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(GeocodeService.ResponseSummary), Action:="http://dev.virtualearth.net/webservices/v1/geocode/contracts/IGeocodeService/Geoc"& _ 
            "odeResponseSummaryFault", Name:="ResponseSummary", [Namespace]:="http://dev.virtualearth.net/webservices/v1/common")>  _
        Function Geocode(ByVal request As GeocodeService.GeocodeRequest) As GeocodeService.GeocodeResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://dev.virtualearth.net/webservices/v1/geocode/contracts/IGeocodeService/Geoc"& _ 
            "ode", ReplyAction:="http://dev.virtualearth.net/webservices/v1/geocode/contracts/IGeocodeService/Geoc"& _ 
            "odeResponse")>  _
        Function GeocodeAsync(ByVal request As GeocodeService.GeocodeRequest) As System.Threading.Tasks.Task(Of GeocodeService.GeocodeResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://dev.virtualearth.net/webservices/v1/geocode/contracts/IGeocodeService/Reve"& _ 
            "rseGeocode", ReplyAction:="http://dev.virtualearth.net/webservices/v1/geocode/contracts/IGeocodeService/Reve"& _ 
            "rseGeocodeResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(GeocodeService.ResponseSummary), Action:="http://dev.virtualearth.net/webservices/v1/geocode/contracts/IGeocodeService/Reve"& _ 
            "rseGeocodeResponseSummaryFault", Name:="ResponseSummary", [Namespace]:="http://dev.virtualearth.net/webservices/v1/common")>  _
        Function ReverseGeocode(ByVal request As GeocodeService.ReverseGeocodeRequest) As GeocodeService.GeocodeResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://dev.virtualearth.net/webservices/v1/geocode/contracts/IGeocodeService/Reve"& _ 
            "rseGeocode", ReplyAction:="http://dev.virtualearth.net/webservices/v1/geocode/contracts/IGeocodeService/Reve"& _ 
            "rseGeocodeResponse")>  _
        Function ReverseGeocodeAsync(ByVal request As GeocodeService.ReverseGeocodeRequest) As System.Threading.Tasks.Task(Of GeocodeService.GeocodeResponse)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IGeocodeServiceChannel
        Inherits GeocodeService.IGeocodeService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class GeocodeServiceClient
        Inherits System.ServiceModel.ClientBase(Of GeocodeService.IGeocodeService)
        Implements GeocodeService.IGeocodeService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function Geocode(ByVal request As GeocodeService.GeocodeRequest) As GeocodeService.GeocodeResponse Implements GeocodeService.IGeocodeService.Geocode
            Return MyBase.Channel.Geocode(request)
        End Function
        
        Public Function GeocodeAsync(ByVal request As GeocodeService.GeocodeRequest) As System.Threading.Tasks.Task(Of GeocodeService.GeocodeResponse) Implements GeocodeService.IGeocodeService.GeocodeAsync
            Return MyBase.Channel.GeocodeAsync(request)
        End Function
        
        Public Function ReverseGeocode(ByVal request As GeocodeService.ReverseGeocodeRequest) As GeocodeService.GeocodeResponse Implements GeocodeService.IGeocodeService.ReverseGeocode
            Return MyBase.Channel.ReverseGeocode(request)
        End Function
        
        Public Function ReverseGeocodeAsync(ByVal request As GeocodeService.ReverseGeocodeRequest) As System.Threading.Tasks.Task(Of GeocodeService.GeocodeResponse) Implements GeocodeService.IGeocodeService.ReverseGeocodeAsync
            Return MyBase.Channel.ReverseGeocodeAsync(request)
        End Function
    End Class
End Namespace
